services:
  - type: web
    name: echosign-admin
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn voice_server:app -w 2 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: S3_BUCKET_NAME
        sync: false
      - key: AWS_DEFAULT_REGION
        value: eu-north-1
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 10000
